name: Run URL Checker Tests

# Trigger the workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
    paths:
      - 'src/url-checker.ts'
      - 'src/url-checker.test.ts'
  pull_request:
    branches:
      - main
    paths:
      - 'src/url-checker.ts'
      - 'src/url-checker.test.ts'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.x'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run URL checker tests
      - name: Run URL checker tests
        run: npm run test:url
